# Generated by Django 5.1.3 on 2024-11-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_cms_app', '0003_courses_price_name_currency_alter_courses_price_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='trainee',
            name='profile_pic',
            field=models.ImageField(default='blank.webp', upload_to='profile_pic'),
        ),
        migrations.AddField(
            model_name='trainers',
            name='profile_pic',
            field=models.ImageField(default='blank.webp', upload_to='profile_pic'),
        ),
    ]
