# Generated by Django 5.1.3 on 2024-11-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_cms_app', '0004_remove_customuser_profile_pic_trainee_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='profile_pic',
            field=models.ImageField(default='blank.webp', upload_to='profile_pic'),
        ),
    ]
